name: "Runner CI Java Tests"
description: "Runner CI Java Tests"
inputs:
  module-name:
    required: true
  module-folder:
    required: true

runs:
  using: "composite"
  steps:
    - name: "Java TEST"
      shell: bash
      run: |
        echo "Unfortunately this has not been implemented yet"

