name: cards-migration

on:
  - pull_request_target

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: pip install -r requirements.txt
      - run: python3 tools/git_hooks/cards_migration.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}