name: Sonar Scan
on:
  push:
    branches:
      - h-chlor-patch-1 # test local branch
      - htrueman/sonarqube-qa-github-jobs
      - master # or the name of your main branch
jobs:
  sonar-scan:
    name: Sonar Scan Python Connectors
    runs-on: ubuntu-latest
    environment: more-secrets
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: sonarsource/sonarqube-scan-action@master
        with:
          projectBaseDir: airbyte-integrations/connectors
          # -Dsonar.tests=.
          # -Dsonar.test.inclusions=**/unit_tests/**
          args: >
            -Dsonar.projectKey=airbite-python-connectors
            -Dsonar.exclusions=**/*.java
            -Dsonar.verbose=true
            -Dsonar.language=py
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.analysis.mode=
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: SonarQube Quality Gate check
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
